# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(max_length=200)),
                ('show_date', models.DateTimeField(verbose_name='show date')),
            ],
        ),
    ]
